# Site settings
title: Subscription Boxes and Gifts 
email: subscriptionboxesandgifts@gmail.com
description: The best subscription boxes and 'of the month clubs' for christmas gifts this year.
url: "http://subscriptionboxesandgifts.com"
twitter_username: alexjdenne
baseurl: '/subscriptionboxesandgifts'

# Build settings
markdown: kramdown
permalink: /:title